-- AI(Gemini) 호출 사용량 로그. gemini-insight Edge Function의 레이트리밋 근거 테이블.
--
-- RLS를 켜되 정책은 만들지 않는다. 정책이 없는 RLS 테이블은 anon/authenticated에게
-- 전면 차단되고 service_role만 우회한다. Edge Function은 service_role로 기록하므로
-- 정상 동작하면서, 클라이언트는 자기 사용량 로그를 읽거나 지워서 제한을 우회할 수 없다.

CREATE TABLE IF NOT EXISTS public.ai_usage_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  kind TEXT NOT NULL,
  called_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ai_usage_log_kind_check CHECK (kind IN ('insight', 'chat'))
);

-- 레이트리밋 조회 패턴: 특정 사용자의 최근 60초 호출 수
CREATE INDEX IF NOT EXISTS idx_ai_usage_log_user_called_at
  ON public.ai_usage_log (user_id, called_at DESC);

ALTER TABLE public.ai_usage_log ENABLE ROW LEVEL SECURITY;
