-- Supabase-backed feature permissions and RLS hardening.
-- The permission matrix is scoped per factory. Admin is the immutable break-glass role.

CREATE TABLE IF NOT EXISTS public.app_features (
  key TEXT PRIMARY KEY,
  label_key TEXT NOT NULL,
  route TEXT NOT NULL UNIQUE,
  sort_order INTEGER NOT NULL UNIQUE,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT app_features_key_format CHECK (key ~ '^[a-z][A-Za-z]+$')
);

CREATE TABLE IF NOT EXISTS public.role_feature_permissions (
  factory_id TEXT NOT NULL REFERENCES public.factories(id) ON UPDATE CASCADE ON DELETE CASCADE,
  role public.user_role NOT NULL,
  feature_key TEXT NOT NULL REFERENCES public.app_features(key) ON UPDATE CASCADE ON DELETE CASCADE,
  allowed BOOLEAN NOT NULL DEFAULT false,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  PRIMARY KEY (factory_id, role, feature_key)
);

CREATE INDEX IF NOT EXISTS idx_role_feature_permissions_lookup
  ON public.role_feature_permissions (factory_id, role, feature_key)
  INCLUDE (allowed);

CREATE TABLE IF NOT EXISTS public.permission_audit (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  factory_id TEXT NOT NULL REFERENCES public.factories(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  role public.user_role NOT NULL,
  feature_key TEXT NOT NULL REFERENCES public.app_features(key) ON UPDATE CASCADE ON DELETE RESTRICT,
  old_allowed BOOLEAN,
  new_allowed BOOLEAN NOT NULL,
  changed_by UUID NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
  changed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_permission_audit_factory_changed_at
  ON public.permission_audit (factory_id, changed_at DESC);

INSERT INTO public.app_features (key, label_key, route, sort_order) VALUES
  ('dashboard', 'nav.dashboard', '/dashboard', 10),
  ('inspection', 'nav.inspection', '/inspection', 20),
  ('defects', 'nav.defects', '/defects', 30),
  ('analytics', 'nav.analytics', '/analytics', 40),
  ('spc', 'nav.spc', '/spc', 50),
  ('reports', 'nav.reports', '/reports', 60),
  ('aiInsights', 'nav.aiInsights', '/ai-insights', 70),
  ('management', 'nav.management', '/management', 80),
  ('userManagement', 'nav.userManagement', '/users', 90)
ON CONFLICT (key) DO UPDATE SET
  label_key = EXCLUDED.label_key,
  route = EXCLUDED.route,
  sort_order = EXCLUDED.sort_order,
  is_active = true;

WITH defaults(role, feature_key, allowed) AS (
  VALUES
    ('admin'::public.user_role, 'dashboard', true),
    ('admin'::public.user_role, 'inspection', true),
    ('admin'::public.user_role, 'defects', true),
    ('admin'::public.user_role, 'analytics', true),
    ('admin'::public.user_role, 'spc', true),
    ('admin'::public.user_role, 'reports', true),
    ('admin'::public.user_role, 'aiInsights', true),
    ('admin'::public.user_role, 'management', true),
    ('admin'::public.user_role, 'userManagement', true),
    ('manager'::public.user_role, 'dashboard', true),
    ('manager'::public.user_role, 'inspection', true),
    ('manager'::public.user_role, 'defects', true),
    ('manager'::public.user_role, 'analytics', true),
    ('manager'::public.user_role, 'spc', true),
    ('manager'::public.user_role, 'reports', true),
    ('manager'::public.user_role, 'aiInsights', true),
    ('manager'::public.user_role, 'management', true),
    ('manager'::public.user_role, 'userManagement', true),
    ('inspector'::public.user_role, 'dashboard', true),
    ('inspector'::public.user_role, 'inspection', true),
    ('inspector'::public.user_role, 'defects', true),
    ('inspector'::public.user_role, 'analytics', false),
    ('inspector'::public.user_role, 'spc', false),
    ('inspector'::public.user_role, 'reports', false),
    ('inspector'::public.user_role, 'aiInsights', false),
    ('inspector'::public.user_role, 'management', false),
    ('inspector'::public.user_role, 'userManagement', false)
)
INSERT INTO public.role_feature_permissions (factory_id, role, feature_key, allowed)
SELECT f.id, d.role, d.feature_key, d.allowed
FROM public.factories f
CROSS JOIN defaults d
ON CONFLICT (factory_id, role, feature_key) DO NOTHING;

CREATE OR REPLACE FUNCTION public.current_user_role()
RETURNS public.user_role
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
  SELECT u.role
  FROM public.users u
  WHERE u.id = auth.uid()
$$;

CREATE OR REPLACE FUNCTION public.current_user_factory_id()
RETURNS TEXT
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
  SELECT u.factory_id
  FROM public.users u
  WHERE u.id = auth.uid()
$$;

CREATE OR REPLACE FUNCTION public.has_feature_permission(
  p_feature_key TEXT,
  p_factory_id TEXT DEFAULT NULL
)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
  SELECT COALESCE((
    SELECT
      u.role = 'admin'::public.user_role
      OR (
        u.factory_id = COALESCE(p_factory_id, u.factory_id)
        AND EXISTS (
          SELECT 1
          FROM public.role_feature_permissions rfp
          JOIN public.app_features af ON af.key = rfp.feature_key AND af.is_active
          WHERE rfp.factory_id = u.factory_id
            AND rfp.role = u.role
            AND rfp.feature_key = p_feature_key
            AND rfp.allowed
        )
      )
    FROM public.users u
    WHERE u.id = auth.uid()
  ), false)
$$;

CREATE OR REPLACE FUNCTION public.has_any_feature_permission(
  p_feature_keys TEXT[],
  p_factory_id TEXT DEFAULT NULL
)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM unnest(p_feature_keys) AS feature_key
    WHERE public.has_feature_permission(feature_key, p_factory_id)
  )
$$;

CREATE OR REPLACE FUNCTION public.can_access_factory(p_factory_id TEXT)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
  SELECT COALESCE((
    SELECT u.role = 'admin'::public.user_role OR u.factory_id = p_factory_id
    FROM public.users u
    WHERE u.id = auth.uid()
  ), false)
$$;

CREATE OR REPLACE FUNCTION public.get_my_permissions()
RETURNS TABLE(feature_key TEXT)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
  SELECT af.key
  FROM public.app_features af
  JOIN public.users u ON u.id = auth.uid()
  LEFT JOIN public.role_feature_permissions rfp
    ON rfp.factory_id = u.factory_id
   AND rfp.role = u.role
   AND rfp.feature_key = af.key
  WHERE af.is_active
    AND (u.role = 'admin'::public.user_role OR COALESCE(rfp.allowed, false))
  ORDER BY af.sort_order
$$;

CREATE OR REPLACE FUNCTION public.get_role_permissions(p_factory_id TEXT)
RETURNS TABLE(
  factory_id TEXT,
  role public.user_role,
  feature_key TEXT,
  allowed BOOLEAN,
  updated_at TIMESTAMPTZ,
  updated_by UUID
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
BEGIN
  IF auth.uid() IS NULL OR NOT (
    public.current_user_role() = 'admin'::public.user_role
    OR (
      public.current_user_factory_id() = p_factory_id
      AND public.has_feature_permission('userManagement', p_factory_id)
    )
  ) THEN
    RAISE EXCEPTION 'permission denied' USING ERRCODE = '42501';
  END IF;

  RETURN QUERY
  SELECT
    rfp.factory_id,
    rfp.role,
    rfp.feature_key,
    CASE WHEN rfp.role = 'admin'::public.user_role THEN true ELSE rfp.allowed END,
    rfp.updated_at,
    rfp.updated_by
  FROM public.role_feature_permissions rfp
  JOIN public.app_features af ON af.key = rfp.feature_key AND af.is_active
  WHERE rfp.factory_id = p_factory_id
  ORDER BY af.sort_order, rfp.role;
END
$$;

-- Operational screens need names and roles, but must not receive account email
-- addresses or other profile fields. Keep this projection behind a bounded RPC.
CREATE OR REPLACE FUNCTION public.get_user_directory()
RETURNS TABLE(
  id UUID,
  name TEXT,
  role public.user_role,
  factory_id TEXT
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
  SELECT u.id, u.name, u.role, u.factory_id
  FROM public.users u
  JOIN public.users caller ON caller.id = auth.uid()
  WHERE auth.uid() IS NOT NULL
    AND (
      caller.role = 'admin'::public.user_role
      OR (
        u.factory_id = caller.factory_id
        AND public.has_any_feature_permission(
          ARRAY['inspection','defects','analytics','reports','aiInsights','userManagement'],
          caller.factory_id
        )
      )
    )
  ORDER BY u.name, u.id
$$;

CREATE OR REPLACE FUNCTION public.set_role_permissions(
  p_factory_id TEXT,
  p_changes JSONB
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  change_item JSONB;
  target_role public.user_role;
  target_feature TEXT;
  target_allowed BOOLEAN;
  previous_allowed BOOLEAN;
BEGIN
  IF auth.uid() IS NULL OR public.current_user_role() <> 'admin'::public.user_role THEN
    RAISE EXCEPTION 'only administrators can change permissions' USING ERRCODE = '42501';
  END IF;

  IF NOT EXISTS (SELECT 1 FROM public.factories f WHERE f.id = p_factory_id) THEN
    RAISE EXCEPTION 'unknown factory: %', p_factory_id USING ERRCODE = '22023';
  END IF;

  IF jsonb_typeof(p_changes) <> 'array' THEN
    RAISE EXCEPTION 'p_changes must be a JSON array' USING ERRCODE = '22023';
  END IF;

  FOR change_item IN SELECT value FROM jsonb_array_elements(p_changes)
  LOOP
    previous_allowed := NULL;

    BEGIN
      target_role := (change_item ->> 'role')::public.user_role;
      target_feature := change_item ->> 'feature_key';
      target_allowed := (change_item ->> 'allowed')::BOOLEAN;
    EXCEPTION WHEN OTHERS THEN
      RAISE EXCEPTION 'invalid permission change: %', change_item USING ERRCODE = '22023';
    END;

    IF target_role = 'admin'::public.user_role THEN
      RAISE EXCEPTION 'administrator permissions are immutable' USING ERRCODE = '22023';
    END IF;

    IF target_role IS NULL OR target_allowed IS NULL THEN
      RAISE EXCEPTION 'role and allowed are required: %', change_item USING ERRCODE = '22023';
    END IF;

    IF target_feature IS NULL OR NOT EXISTS (
      SELECT 1 FROM public.app_features af WHERE af.key = target_feature AND af.is_active
    ) THEN
      RAISE EXCEPTION 'unknown feature: %', target_feature USING ERRCODE = '22023';
    END IF;

    SELECT rfp.allowed
    INTO previous_allowed
    FROM public.role_feature_permissions rfp
    WHERE rfp.factory_id = p_factory_id
      AND rfp.role = target_role
      AND rfp.feature_key = target_feature
    FOR UPDATE;

    IF previous_allowed IS DISTINCT FROM target_allowed THEN
      INSERT INTO public.role_feature_permissions (
        factory_id, role, feature_key, allowed, updated_at, updated_by
      ) VALUES (
        p_factory_id, target_role, target_feature, target_allowed, now(), auth.uid()
      )
      ON CONFLICT (factory_id, role, feature_key) DO UPDATE SET
        allowed = EXCLUDED.allowed,
        updated_at = EXCLUDED.updated_at,
        updated_by = EXCLUDED.updated_by;

      INSERT INTO public.permission_audit (
        factory_id, role, feature_key, old_allowed, new_allowed, changed_by
      ) VALUES (
        p_factory_id, target_role, target_feature, previous_allowed, target_allowed, auth.uid()
      );
    END IF;
  END LOOP;
END
$$;

-- Public TV monitor receives only the bounded, non-user fields required by its UI.
-- Base tables remain unavailable to anon.
CREATE OR REPLACE FUNCTION public.get_public_monitor_data(
  p_factory_id TEXT,
  p_start_at TIMESTAMPTZ,
  p_end_at TIMESTAMPTZ
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  IF p_factory_id IS NULL OR NOT EXISTS (
    SELECT 1 FROM public.factories f
    WHERE f.id = p_factory_id AND f.is_active = true
  ) THEN
    RAISE EXCEPTION 'invalid or inactive factory' USING ERRCODE = '22023';
  END IF;

  IF p_start_at IS NULL OR p_end_at IS NULL
     OR p_end_at <= p_start_at
     OR p_end_at > p_start_at + interval '32 days'
     OR p_start_at < now() - interval '32 days'
     OR p_start_at > now() + interval '1 day' THEN
    RAISE EXCEPTION 'invalid monitor date range' USING ERRCODE = '22023';
  END IF;

  RETURN jsonb_build_object(
    'defects', COALESCE((
      SELECT jsonb_agg(jsonb_build_object(
        'id', d.id,
        'created_at', d.created_at,
        'inspection_id', d.inspection_id,
        'model_id', d.model_id,
        'defect_type', d.defect_type
      ) ORDER BY d.created_at DESC)
      FROM public.defects d
      WHERE d.factory_id = p_factory_id
        AND d.created_at >= p_start_at
        AND d.created_at <= p_end_at
    ), '[]'::jsonb),
    'inspections', COALESCE((
      SELECT jsonb_agg(jsonb_build_object('id', i.id, 'machine_id', i.machine_id))
      FROM public.inspections i
      WHERE i.factory_id = p_factory_id
        AND EXISTS (
          SELECT 1 FROM public.defects d
          WHERE d.inspection_id = i.id
            AND d.factory_id = p_factory_id
            AND d.created_at >= p_start_at
            AND d.created_at <= p_end_at
        )
    ), '[]'::jsonb),
    'machines', COALESCE((
      SELECT jsonb_agg(jsonb_build_object('id', m.id, 'name', m.name) ORDER BY m.name)
      FROM public.machines m
      WHERE m.factory_id = p_factory_id
        AND m.status = 'active'
        AND EXISTS (
          SELECT 1
          FROM public.inspections i
          JOIN public.defects d ON d.inspection_id = i.id
          WHERE i.machine_id = m.id
            AND i.factory_id = p_factory_id
            AND d.factory_id = p_factory_id
            AND d.created_at >= p_start_at
            AND d.created_at <= p_end_at
        )
    ), '[]'::jsonb),
    'product_models', COALESCE((
      SELECT jsonb_agg(jsonb_build_object('id', pm.id, 'code', pm.code) ORDER BY pm.code)
      FROM public.product_models pm
      WHERE EXISTS (
        SELECT 1 FROM public.defects d
        WHERE d.model_id = pm.id
          AND d.factory_id = p_factory_id
          AND d.created_at >= p_start_at
          AND d.created_at <= p_end_at
      )
    ), '[]'::jsonb),
    'defect_types', COALESCE((
      SELECT jsonb_agg(jsonb_build_object('id', dt.id, 'code', dt.code, 'name', dt.name) ORDER BY dt.code)
      FROM public.defect_types dt
      WHERE dt.is_active = true
        AND EXISTS (
          SELECT 1 FROM public.defects d
          WHERE (d.defect_type = dt.id::text OR d.defect_type = dt.code)
            AND d.factory_id = p_factory_id
            AND d.created_at >= p_start_at
            AND d.created_at <= p_end_at
        )
    ), '[]'::jsonb)
  );
END
$$;

REVOKE ALL ON public.app_features FROM anon;
REVOKE ALL ON public.role_feature_permissions FROM anon;
REVOKE ALL ON public.permission_audit FROM anon;
REVOKE ALL ON public.app_features FROM authenticated;
REVOKE ALL ON public.role_feature_permissions FROM authenticated;
REVOKE ALL ON public.permission_audit FROM authenticated;
GRANT SELECT ON public.app_features TO authenticated;
GRANT SELECT ON public.role_feature_permissions TO authenticated;
GRANT SELECT ON public.permission_audit TO authenticated;

REVOKE ALL ON FUNCTION public.current_user_role() FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.current_user_factory_id() FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.has_feature_permission(TEXT, TEXT) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.has_any_feature_permission(TEXT[], TEXT) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.can_access_factory(TEXT) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.get_my_permissions() FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.get_user_directory() FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.get_role_permissions(TEXT) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.set_role_permissions(TEXT, JSONB) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.get_public_monitor_data(TEXT, TIMESTAMPTZ, TIMESTAMPTZ) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.current_user_role() TO authenticated;
GRANT EXECUTE ON FUNCTION public.current_user_factory_id() TO authenticated;
GRANT EXECUTE ON FUNCTION public.has_feature_permission(TEXT, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.has_any_feature_permission(TEXT[], TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.can_access_factory(TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_my_permissions() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_user_directory() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_role_permissions(TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.set_role_permissions(TEXT, JSONB) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_public_monitor_data(TEXT, TIMESTAMPTZ, TIMESTAMPTZ) TO anon, authenticated;

ALTER TABLE public.app_features ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.role_feature_permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.permission_audit ENABLE ROW LEVEL SECURITY;

CREATE POLICY app_features_read ON public.app_features
  FOR SELECT TO authenticated
  USING (is_active);

CREATE POLICY role_permissions_read ON public.role_feature_permissions
  FOR SELECT TO authenticated
  USING (
    public.current_user_role() = 'admin'::public.user_role
    OR (
      factory_id = public.current_user_factory_id()
      AND (
        role = public.current_user_role()
        OR public.has_feature_permission('userManagement', factory_id)
      )
    )
  );

CREATE POLICY permission_audit_read ON public.permission_audit
  FOR SELECT TO authenticated
  USING (public.current_user_role() = 'admin'::public.user_role);

-- Remove every existing permissive policy on application tables before recreating them.
DO $$
DECLARE
  policy_record RECORD;
BEGIN
  FOR policy_record IN
    SELECT schemaname, tablename, policyname
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = ANY (ARRAY[
        'factories', 'machines', 'inspections', 'inspection_results', 'defects',
        'product_models', 'inspection_items', 'inspection_processes', 'defect_types',
        'spc_alerts', 'users'
      ])
  LOOP
    EXECUTE format(
      'DROP POLICY IF EXISTS %I ON %I.%I',
      policy_record.policyname,
      policy_record.schemaname,
      policy_record.tablename
    );
  END LOOP;
END
$$;

ALTER TABLE public.factories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.machines ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inspections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inspection_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.defects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_models ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inspection_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inspection_processes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.defect_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.spc_alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.factories, public.machines, public.inspections,
  public.inspection_results, public.defects, public.product_models,
  public.inspection_items, public.inspection_processes, public.defect_types,
  public.spc_alerts, public.users FROM anon;

REVOKE ALL ON TABLE public.factories, public.machines, public.inspections,
  public.inspection_results, public.defects, public.product_models,
  public.inspection_items, public.inspection_processes, public.defect_types,
  public.spc_alerts, public.users FROM authenticated;

GRANT SELECT ON TABLE public.factories TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.machines, public.inspections,
  public.defects, public.product_models, public.inspection_items,
  public.inspection_processes, public.defect_types, public.spc_alerts, public.users
  TO authenticated;
GRANT SELECT, INSERT ON TABLE public.inspection_results TO authenticated;

CREATE POLICY factories_select ON public.factories
  FOR SELECT TO authenticated
  USING (public.can_access_factory(id));

CREATE POLICY machines_select ON public.machines
  FOR SELECT TO authenticated
  USING (
    public.can_access_factory(factory_id)
    AND public.has_any_feature_permission(
      ARRAY['dashboard','inspection','defects','analytics','spc','reports','aiInsights','management'],
      factory_id
    )
  );
CREATE POLICY machines_insert ON public.machines
  FOR INSERT TO authenticated
  WITH CHECK (public.can_access_factory(factory_id) AND public.has_feature_permission('management', factory_id));
CREATE POLICY machines_update ON public.machines
  FOR UPDATE TO authenticated
  USING (public.can_access_factory(factory_id) AND public.has_feature_permission('management', factory_id))
  WITH CHECK (public.can_access_factory(factory_id) AND public.has_feature_permission('management', factory_id));
CREATE POLICY machines_delete ON public.machines
  FOR DELETE TO authenticated
  USING (public.can_access_factory(factory_id) AND public.has_feature_permission('management', factory_id));

CREATE POLICY inspections_select ON public.inspections
  FOR SELECT TO authenticated
  USING (
    public.can_access_factory(factory_id)
    AND public.has_any_feature_permission(
      ARRAY['dashboard','inspection','defects','analytics','spc','reports','aiInsights'],
      factory_id
    )
  );
CREATE POLICY inspections_insert ON public.inspections
  FOR INSERT TO authenticated
  WITH CHECK (
    public.can_access_factory(factory_id)
    AND public.has_feature_permission('inspection', factory_id)
    AND (
      user_id = auth.uid()
      OR (
        public.current_user_role() IN ('admin'::public.user_role, 'manager'::public.user_role)
        AND EXISTS (
          SELECT 1 FROM public.users target_user
          WHERE target_user.id = user_id
            AND (
              public.current_user_role() = 'admin'::public.user_role
              OR target_user.factory_id = inspections.factory_id
            )
        )
      )
    )
  );
CREATE POLICY inspections_update ON public.inspections
  FOR UPDATE TO authenticated
  USING (
    public.can_access_factory(factory_id)
    AND public.has_feature_permission('inspection', factory_id)
    AND (user_id = auth.uid() OR public.current_user_role() IN ('admin'::public.user_role, 'manager'::public.user_role))
  )
  WITH CHECK (
    public.can_access_factory(factory_id)
    AND public.has_feature_permission('inspection', factory_id)
    AND (
      user_id = auth.uid()
      OR public.current_user_role() = 'admin'::public.user_role
      OR (
        public.current_user_role() = 'manager'::public.user_role
        AND EXISTS (
          SELECT 1 FROM public.users target_user
          WHERE target_user.id = user_id
            AND target_user.factory_id = inspections.factory_id
        )
      )
    )
  );
CREATE POLICY inspections_delete ON public.inspections
  FOR DELETE TO authenticated
  USING (
    public.can_access_factory(factory_id)
    AND public.has_feature_permission('inspection', factory_id)
    AND (user_id = auth.uid() OR public.current_user_role() IN ('admin'::public.user_role, 'manager'::public.user_role))
  );

CREATE POLICY inspection_results_select ON public.inspection_results
  FOR SELECT TO authenticated
  USING (EXISTS (
    SELECT 1 FROM public.inspections i
    WHERE i.id = inspection_id
      AND public.can_access_factory(i.factory_id)
      AND public.has_any_feature_permission(ARRAY['inspection','analytics','spc','reports','aiInsights'], i.factory_id)
  ));
CREATE POLICY inspection_results_insert ON public.inspection_results
  FOR INSERT TO authenticated
  WITH CHECK (EXISTS (
    SELECT 1 FROM public.inspections i
    WHERE i.id = inspection_id
      AND public.can_access_factory(i.factory_id)
      AND public.has_feature_permission('inspection', i.factory_id)
      AND (i.user_id = auth.uid() OR public.current_user_role() IN ('admin'::public.user_role, 'manager'::public.user_role))
  ));

CREATE POLICY defects_select ON public.defects
  FOR SELECT TO authenticated
  USING (
    public.can_access_factory(factory_id)
    AND public.has_any_feature_permission(
      ARRAY['dashboard','defects','analytics','spc','reports','aiInsights'],
      factory_id
    )
  );
CREATE POLICY defects_insert ON public.defects
  FOR INSERT TO authenticated
  WITH CHECK (
    public.can_access_factory(factory_id)
    AND public.has_any_feature_permission(ARRAY['inspection','defects'], factory_id)
    AND EXISTS (
      SELECT 1 FROM public.inspections i
      WHERE i.id = inspection_id
        AND i.factory_id = defects.factory_id
        AND (i.user_id = auth.uid() OR public.current_user_role() IN ('admin'::public.user_role, 'manager'::public.user_role))
    )
  );
CREATE POLICY defects_update ON public.defects
  FOR UPDATE TO authenticated
  USING (
    public.can_access_factory(factory_id)
    AND public.has_feature_permission('defects', factory_id)
    AND EXISTS (
      SELECT 1 FROM public.inspections i
      WHERE i.id = inspection_id
        AND (i.user_id = auth.uid() OR public.current_user_role() IN ('admin'::public.user_role, 'manager'::public.user_role))
    )
  )
  WITH CHECK (
    public.can_access_factory(factory_id)
    AND public.has_feature_permission('defects', factory_id)
    AND EXISTS (
      SELECT 1 FROM public.inspections i
      WHERE i.id = inspection_id
        AND i.factory_id = defects.factory_id
        AND (i.user_id = auth.uid() OR public.current_user_role() IN ('admin'::public.user_role, 'manager'::public.user_role))
    )
  );
CREATE POLICY defects_delete ON public.defects
  FOR DELETE TO authenticated
  USING (
    public.can_access_factory(factory_id)
    AND public.has_feature_permission('defects', factory_id)
    AND EXISTS (
      SELECT 1 FROM public.inspections i
      WHERE i.id = inspection_id
        AND (i.user_id = auth.uid() OR public.current_user_role() IN ('admin'::public.user_role, 'manager'::public.user_role))
    )
  );

CREATE POLICY spc_alerts_select ON public.spc_alerts
  FOR SELECT TO authenticated
  USING (public.can_access_factory(factory_id) AND public.has_feature_permission('spc', factory_id));
CREATE POLICY spc_alerts_insert ON public.spc_alerts
  FOR INSERT TO authenticated
  WITH CHECK (public.can_access_factory(factory_id) AND public.has_feature_permission('spc', factory_id));
CREATE POLICY spc_alerts_update ON public.spc_alerts
  FOR UPDATE TO authenticated
  USING (public.can_access_factory(factory_id) AND public.has_feature_permission('spc', factory_id))
  WITH CHECK (public.can_access_factory(factory_id) AND public.has_feature_permission('spc', factory_id));
CREATE POLICY spc_alerts_delete ON public.spc_alerts
  FOR DELETE TO authenticated
  USING (public.can_access_factory(factory_id) AND public.has_feature_permission('spc', factory_id));

-- Shared reference data must remain readable by operational features.
CREATE POLICY product_models_select ON public.product_models
  FOR SELECT TO authenticated
  USING (public.has_any_feature_permission(ARRAY['dashboard','inspection','defects','analytics','spc','reports','aiInsights','management']));
CREATE POLICY product_models_write ON public.product_models
  FOR ALL TO authenticated
  USING (public.current_user_role() = 'admin'::public.user_role)
  WITH CHECK (public.current_user_role() = 'admin'::public.user_role);

CREATE POLICY inspection_items_select ON public.inspection_items
  FOR SELECT TO authenticated
  USING (public.has_any_feature_permission(ARRAY['inspection','analytics','spc','reports','management']));
CREATE POLICY inspection_items_write ON public.inspection_items
  FOR ALL TO authenticated
  USING (public.current_user_role() = 'admin'::public.user_role)
  WITH CHECK (public.current_user_role() = 'admin'::public.user_role);

CREATE POLICY inspection_processes_select ON public.inspection_processes
  FOR SELECT TO authenticated
  USING (public.has_any_feature_permission(ARRAY['inspection','analytics','spc','reports','management']));
CREATE POLICY inspection_processes_write ON public.inspection_processes
  FOR ALL TO authenticated
  USING (public.current_user_role() = 'admin'::public.user_role)
  WITH CHECK (public.current_user_role() = 'admin'::public.user_role);

CREATE POLICY defect_types_select ON public.defect_types
  FOR SELECT TO authenticated
  USING (public.has_any_feature_permission(ARRAY['dashboard','inspection','defects','analytics','reports','management']));
CREATE POLICY defect_types_write ON public.defect_types
  FOR ALL TO authenticated
  USING (public.current_user_role() = 'admin'::public.user_role)
  WITH CHECK (public.current_user_role() = 'admin'::public.user_role);

CREATE POLICY users_select ON public.users
  FOR SELECT TO authenticated
  USING (
    id = auth.uid()
    OR public.current_user_role() = 'admin'::public.user_role
    OR (
      factory_id = public.current_user_factory_id()
      AND public.has_feature_permission('userManagement', factory_id)
    )
  );
CREATE POLICY users_insert ON public.users
  FOR INSERT TO authenticated
  WITH CHECK (
    public.has_feature_permission('userManagement', factory_id)
    AND (
      public.current_user_role() = 'admin'::public.user_role
      OR (
        public.current_user_role() = 'manager'::public.user_role
        AND role = 'inspector'::public.user_role
        AND factory_id = public.current_user_factory_id()
      )
    )
  );
CREATE POLICY users_update ON public.users
  FOR UPDATE TO authenticated
  USING (
    public.has_feature_permission('userManagement', factory_id)
    AND (
      public.current_user_role() = 'admin'::public.user_role
      OR (
        public.current_user_role() = 'manager'::public.user_role
        AND role = 'inspector'::public.user_role
        AND factory_id = public.current_user_factory_id()
      )
    )
  )
  WITH CHECK (
    public.has_feature_permission('userManagement', factory_id)
    AND (
      public.current_user_role() = 'admin'::public.user_role
      OR (
        public.current_user_role() = 'manager'::public.user_role
        AND role = 'inspector'::public.user_role
        AND factory_id = public.current_user_factory_id()
      )
    )
  );
CREATE POLICY users_delete ON public.users
  FOR DELETE TO authenticated
  USING (
    id <> auth.uid()
    AND public.has_feature_permission('userManagement', factory_id)
    AND (
      public.current_user_role() = 'admin'::public.user_role
      OR (
        public.current_user_role() = 'manager'::public.user_role
        AND role = 'inspector'::public.user_role
        AND factory_id = public.current_user_factory_id()
      )
    )
  );

-- Quarantine the exposed backup table without deleting recovery data.
DO $$
BEGIN
  IF to_regclass('public.inspection_items_backup_20260606') IS NOT NULL THEN
    EXECUTE 'ALTER TABLE public.inspection_items_backup_20260606 ENABLE ROW LEVEL SECURITY';
    EXECUTE 'REVOKE ALL ON TABLE public.inspection_items_backup_20260606 FROM anon, authenticated';
  END IF;
END
$$;

-- Realtime keeps active sessions synchronized after an administrator saves changes.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND schemaname = 'public'
      AND tablename = 'role_feature_permissions'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.role_feature_permissions;
  END IF;
END
$$;
